server:
  port: ${CONFIG_PORT:8080}

spring:
  cloud:
    gateway:
      routes:
        - id: orderModule
          uri: ${ORDER_SERVICE_URI:http://localhost:8050}
          predicates:
            - Path=/orders/**
        - id: userModule
          uri: ${USER_SERVICE_URI:http://localhost:8070}
          predicates:
            - Path=/users/**
        - id: productModule
          uri: ${PRODUCT_SERVICE_URI:http://localhost:8090}
          predicates:
            - Path=/products/**